# Generated by Django 4.1.1 on 2022-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_participant_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lie_points',
            field=models.IntegerField(default=0),
        ),
    ]
