# Generated by Django 4.1.1 on 2022-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0003_alter_report_lie_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="file",
            field=models.FileField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
