# Generated by Django 4.1.1 on 2022-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_participant_email_alter_participant_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
