# Generated by Django 4.1.1 on 2022-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_alter_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birth_year',
            field=models.IntegerField(),
        ),
    ]
