# Generated by Django 4.1.1 on 2022-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_alter_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdescription',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
