# Generated by Django 4.1.1 on 2022-10-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_pointdescription_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdescription',
            name='text_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
