# Generated by Django 4.1.1 on 2022-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0012_pointdescription_text_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdescription',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Русский'),
        ),
        migrations.AlterField(
            model_name='pointdescription',
            name='text_en',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Английский'),
        ),
    ]
