# Generated by Django 4.1.1 on 2022-10-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0013_alter_pointdescription_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='reportsPDF'),
        ),
    ]
