# Generated by Django 4.1.1 on 2022-10-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0021_alter_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lang',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
