# Generated by Django 4.1.1 on 2022-10-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0022_report_lang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
