# Generated by Django 4.1.1 on 2022-10-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0026_participant_added_project_added_report_added_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True, null=True)),
                ("file", models.FileField(default=None, upload_to="media/reportsPDF/")),
                (
                    "lang",
                    models.CharField(blank=True, default=None, max_length=2, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pdf.project",
                        verbose_name="Проект_групповой отчет",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportGroupSquares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True, null=True)),
                ("square_name", models.CharField(max_length=30)),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pdf.participant",
                        verbose_name="Участник группового отчета",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pdf.reportgroup",
                        verbose_name="Отчет групповой",
                    ),
                ),
            ],
        ),
    ]
