# Generated by Django 4.1.1 on 2022-10-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0030_userprofile_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
