# Generated by Django 4.1.1 on 2022-11-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0031_userprofile_tel"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportgroup",
            name="comments",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Комментарии групповой отчет",
            ),
        ),
        migrations.AlterField(
            model_name="reportgroup",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pdf.project",
                verbose_name="Проект групповой отчет",
            ),
        ),
    ]
