# Generated by Django 4.1.1 on 2022-12-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0035_company_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='name_eng',
            new_name='name_en',
        ),
    ]
