# Generated by Django 4.1.1 on 2022-12-10 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pdf", "0036_rename_name_eng_industry_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="industry",
            name="edited_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="industry",
            name="edited_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Изменено_пользователем",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="industry",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Создано_пользователем",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
