# Generated by Django 4.1.1 on 2022-12-10 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0037_industry_edited_at_industry_edited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='edited_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Изменено_пользователем_роль_сотрудника', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Создано_пользователем_роль_сотрудника', to=settings.AUTH_USER_MODEL),
        ),
    ]
