# Generated by Django 4.1.1 on 2022-12-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0038_employeerole_edited_at_employeerole_edited_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeposition',
            old_name='name_eng',
            new_name='name_en',
        ),
    ]
