# Generated by Django 4.1.1 on 2022-12-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0039_rename_name_eng_employeeposition_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="company_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="company_admin_active",
            field=models.BooleanField(default=False),
        ),
    ]
