# Generated by Django 4.1.1 on 2022-12-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0041_alter_employeeposition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('research_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('public_code', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pdf.company')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='study',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pdf.study'),
        ),
    ]
