# Generated by Django 4.1.1 on 2022-12-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0042_study_report_study"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={
                "verbose_name": "Опросники (study)",
                "verbose_name_plural": "Опросники (studies)",
            },
        ),
    ]
