# Generated by Django 4.1.1 on 2022-12-13 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pdf", "0043_alter_study_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="company",
        ),
        migrations.AddField(
            model_name="participant",
            name="study",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="pdf.study",
            ),
        ),
        migrations.CreateModel(
            name="StudyQuestionGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pdf.section",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pdf.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция вопросов для опросника",
                "verbose_name_plural": "Секции вопросов для опросника",
            },
        ),
    ]
