# Generated by Django 4.1.1 on 2022-12-14 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0044_remove_participant_company_participant_study_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pdf.company",
                verbose_name="Компания",
            ),
        ),
    ]
