# Generated by Django 4.1.1 on 2022-12-14 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0046_study_research_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='sex',
        ),
        migrations.AddField(
            model_name='participant',
            name='invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailSentToParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pdf.participant')),
            ],
            options={
                'verbose_name': 'Письмо отправлено',
                'verbose_name_plural': 'Письма отправленные',
            },
        ),
    ]
