# Generated by Django 4.1.1 on 2022-12-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0047_remove_participant_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник (employee)', 'verbose_name_plural': 'Сотрудники (employee)'},
        ),
    ]
