# Generated by Django 4.1.1 on 2022-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0049_employee_user_alter_employee_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="invitation_sent_datetime",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
