# Generated by Django 4.1.1 on 2022-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0050_participant_invitation_sent_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
