# Generated by Django 4.1.1 on 2023-01-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pdf", "0051_alter_report_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantQuestionGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "question_group_name",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "question_group_code",
                    models.CharField(blank=True, default=None, max_length=2, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа вопросов для участника",
                "verbose_name_plural": "Группы вопросов для участника",
            },
        ),
        migrations.CreateModel(
            name="RawToTPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_points", models.IntegerField(default=0)),
                ("t_point", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Сырые данные в Т баллы",
                "verbose_name_plural": "Сырые данные в Т баллы",
            },
        ),
        migrations.CreateModel(
            name="RawToTPointsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Тип поправки",
                "verbose_name_plural": "Типы поправок",
            },
        ),
        migrations.RemoveField(
            model_name="participant",
            name="finished_at",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="category",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="section",
        ),
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="answered_questions_qnt",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="current_percentage",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="invitation_code",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="send_admin_notification_after_filling_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="total_questions_qnt",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="comments",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Комментарии индивидуальный отчет",
            ),
        ),
        migrations.AddField(
            model_name="reportdata",
            name="category_code",
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="reportdata",
            name="category_name",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="reportdata",
            name="section_code",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="reportdata",
            name="section_name",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="code",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="emailsenttoparticipant",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="industry",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="study",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pdf.study",
            ),
        ),
        migrations.DeleteModel(
            name="StudyQuestionGroups",
        ),
        migrations.AddField(
            model_name="rawtotpoints",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pdf.category",
            ),
        ),
        migrations.AddField(
            model_name="rawtotpoints",
            name="type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pdf.rawtotpointstype",
            ),
        ),
        migrations.AddField(
            model_name="participantquestiongroups",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pdf.participant",
            ),
        ),
    ]
