# Generated by Django 4.1.1 on 2023-01-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0052_participantquestiongroups_rawtotpoints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantquestiongroups",
            name="question_group_code",
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
