# Generated by Django 4.1.5 on 2023-02-23 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0053_alter_participantquestiongroups_question_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='public_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='public_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='public_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='public_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reportgroupsquare',
            name='bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportgroupsquare',
            name='participant_group',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Группа участника'),
        ),
        migrations.AddField(
            model_name='reportgroupsquare',
            name='participant_group_color',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Цвет группы участника'),
        ),
        migrations.AlterField(
            model_name='emailsenttoparticipant',
            name='participant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.participant'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='industry',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.industry', verbose_name='Индустрия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.employeeposition', verbose_name='Позиция участника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.employeerole', verbose_name='Роль участника'),
        ),
        migrations.AlterField(
            model_name='report',
            name='study',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.study'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='category_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.company'),
        ),
        migrations.CreateModel(
            name='StudyQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.section')),
                ('study', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.study')),
            ],
            options={
                'verbose_name': 'Группа вопросов опросника',
                'verbose_name_plural': 'Группы вопросов опросника',
            },
        ),
        migrations.CreateModel(
            name='EmployeeGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('public_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Создано_пользователем_пол_сотрудника', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Изменено_пользователем_пол_сотрудника', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пол участника',
                'verbose_name_plural': 'Пол участников',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.employeegender', verbose_name='Пол'),
        ),
    ]
