# Generated by Django 4.1.5 on 2023-02-23 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0053_alter_participantquestiongroups_question_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='public_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='public_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='public_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='public_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
