# Generated by Django 4.1.5 on 2023-03-02 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pdf", "0055_reportgroupsquare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="birth_year",
            field=models.IntegerField(default=None, null=True, blank=True),
        ),
    ]
