# Generated by Django 4.1.1 on 2024-05-29 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0111_remove_categoryquestions_for_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('square_code', models.CharField(blank=True, max_length=30, null=True)),
                ('square_name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фильтр матрицы',
                'verbose_name_plural': 'Фильтры матриц',
            },
        ),
        migrations.CreateModel(
            name='MatrixFilterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('points_from', models.IntegerField(default=0)),
                ('points_to', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.category')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matrix_filter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.matrixfilter')),
            ],
            options={
                'verbose_name': 'Категория фильтра матрицы',
                'verbose_name_plural': 'Категории фильтров матриц',
            },
        ),
        migrations.CreateModel(
            name='MatrixFilterInclusiveEmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.category')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee_role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pdf.employeerole')),
                ('matrix_filter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.matrixfilter')),
            ],
            options={
                'verbose_name': 'Роль, включенная в фильтр матрицы',
                'verbose_name_plural': 'Роли, включенные в фильтры матриц',
            },
        ),
        migrations.AlterModelOptions(
            name='reportgroup',
            options={'verbose_name': 'Групповой отчет', 'verbose_name_plural': 'Групповые отчеты'},
        ),
        migrations.AlterModelOptions(
            name='reportgroupsquare',
            options={'verbose_name': 'Данные по квадрату групповых отчетов', 'verbose_name_plural': 'Данные по квадратам групповых отчетов'},
        ),
        migrations.DeleteModel(
            name='ParticipantQuestionGroups',
        ),
    ]
