# Generated by Django 4.1.1 on 2024-06-03 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0114_rename_matrixfilterinclusiveemployeerole_matrixfilterinclusiveemployeeposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixFilterParticipantNotDistributed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фильтр матрицы (если ни в один квадрет не попал)',
                'verbose_name_plural': 'Фильтры матриц (если ни в один квадрет не попал)',
            },
        ),
        migrations.AlterField(
            model_name='matrixfiltercategory',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pdf.category'),
        ),
        migrations.CreateModel(
            name='MatrixFilterParticipantNotDistributedEmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee_position', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pdf.employeeposition')),
                ('matrix_filter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.matrixfilterparticipantnotdistributed')),
            ],
            options={
                'verbose_name': 'Должность, включенная в фильтр матрицы',
                'verbose_name_plural': 'Должности, включенные в фильтры матриц',
            },
        ),
    ]
