# Generated by Django 4.1.1 on 2024-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0115_matrixfilterparticipantnotdistributed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixfilterparticipantnotdistributed',
            name='square_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matrixfilterparticipantnotdistributed',
            name='square_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
