# Generated by Django 4.1.1 on 2024-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0116_matrixfilterparticipantnotdistributed_square_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgroupsquare',
            name='square_code',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Квадрат_код'),
        ),
        migrations.AlterField(
            model_name='reportgroupsquare',
            name='square_name',
            field=models.CharField(max_length=30, verbose_name='Квадрат_имя'),
        ),
    ]
