# Generated by Django 4.1.1 on 2024-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0117_reportgroupsquare_square_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgroupsquare',
            name='participant_number',
            field=models.IntegerField(default=0),
        ),
    ]
