# Generated by Django 4.1.1 on 2024-06-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0118_reportgroupsquare_participant_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixfilter',
            name='square_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ReportDataByCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('section_code', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('category_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('category_code', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('t_points', models.IntegerField(default=0)),
                ('report', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.report', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Данные индивидуальных отчетов',
                'verbose_name_plural': 'Данные индивидуальных отчетов',
            },
        ),
    ]
