version: "3.9"

services:
  zetic-report-db:
#    image: postgres:14-alpine
#    volumes:
#      - db_reports:/var/lib/postgresql/data
    image: mysql:5.7
#    command: [--ignore-db-dir=lost+found]
    ports:
      - "3306:3306"
    environment:
#      MYSQL_DATABASE: 'db_reports'
#      MYSQL_USER: 'root'
#      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - db_reports_mysql:/var/lib/my_sql
  zetic-report-web:
    build: .
#      dockerfile: Dockerfile
    command: python /reports/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/reports
    ports:
      - "8000:8000"
#    env_file:
#      - ./.env.dev
    depends_on:
      - zetic-report-db

volumes:
  db_reports_mysql: