version: "3.9"

services:
#  autoheal:
#    restart: always
#    image: willfarrell/autoheal
#    environment:
#      - AUTOHEAL_CONTAINER_LABEL=all
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mysql:8.0.32-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db_reports'
      MYSQL_USER: 'panel'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
    restart: always
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: ['python', 'manage.py', 'runserver', '0.0:8000']
#    healthcheck:
#      retries: 3
#      interval: 5s
#      timeout: 5s
#      start_period: 5s
#      test: ["CMD", "curl", "-f", "http://localhost:8000"]
    volumes:
      - .:/reports
    ports:
      - "8000:8000"
    environment:
      DB_USER: "panel"
      DB_PASSWORD: "password"
      DB_HOST: "db"
      DB_NAME: "db_reports"
      DB_PORT: "3306"
      DEBUG: "1"
#    env_file:
#      - ./.env.dev
    links:
      - db:db
    depends_on:
      - db
      - redis
